Fix docker-build.yml workflow

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -31,9 +31,15 @@ jobs:
       - uses: actions/checkout@v3
       - name: Check
         run: |
-          jq -ecr ".[\"${{ inputs.module }}\"]" nginx-modules.json || echo "" && exit 1
+          jq -ecr ".[\"${{ inputs.module }}\"]" nginx-modules.json
+          if [ $? -ne 0 ]; then
+            echo "Cannot find module ${{ inputs.module }} in nginx-modules.json"
+            exit 1
+          fi
   build:
     runs-on: ubuntu-latest
+    needs:
+      - check
     steps:
       - uses: actions/checkout@v3
 
